Dev containers & GHA Release Flow
sovrin-foundation/sovrin pull request #311
Opened 2023-01-10 08:21 UTC by pSchlarb

2023-01-10 10:42 UTC, pSchlarb commented on .github/workflows/PR.yaml
> +      testAutomationBranch: "sovrin"
Needs to be changed to the correct branch after https://github.com/hyperledger/indy-test-automation/pull/120/ is merged

2023-01-10 15:29 UTC, WadeBarnes requested changes
Some small changes.  We also need to wait until the associate indy-test-automation PR is merged and we tag a version so we can reference the specific version in these workflows.

2023-01-10 15:29 UTC, WadeBarnes commented on updateVersion.py
> +print("Updated version of sovtoken and sovtokenfees metadata.json to: ", version)
```suggestion
print("Updated version of sovrin metadata.json to: ", version)
```

2023-01-10 15:29 UTC, WadeBarnes commented on updateVersion.py
> +    with open('sovrin/metadata.json', 'r') as f:
Would be an idea to extract `sovrin/metadata.json` as a constant so it's defined once.

2023-01-10 15:36 UTC, WadeBarnes commented
Added a ticket for future enhancements; https://github.com/sovrin-foundation/sovrin/issues/312

2023-01-11 13:20 UTC, WadeBarnes reviewed
Latest changes look good.  Should we be targeting the `stable` branch with these changes though?  The `stable` branch is traditionally used for releases.

2023-01-11 16:56 UTC, WadeBarnes approved these changes
Looks good.  The build failures are expected due to the permissions on PRs.  The DinD image is not being pushed to the repo's image repository.  It's passing because it's not trying to push the image.  The client build is failing because the image does not exist yet (expected, will be there once PR is merged).

Just waiting to see the results on https://github.com/pSchlarb/sovrin/actions/runs/3894517829

2023-01-11 19:04 UTC, merged