INDY-1528: Add flag for permission to write txns in ledger
sovrin-foundation/sovrin pull request #76
Opened 2018-07-31 12:47 UTC by ArtObr

Signed-off-by: ArtObr <artemobruchnikov@gmail.com>

2018-08-01 14:13 UTC, dsurnin requested changes

2018-08-01 14:13 UTC, dsurnin commented on build-scripts/ubuntu-1604/postinst
> +
Add closing fi

2018-08-01 14:30 UTC, dsurnin submitted a review, later dismissed

2018-08-09 08:35 UTC, ashcherbakov approved these changes

2018-08-09 08:36 UTC, merged